[package]
name = "nfset"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
curl = { version = "0.4", features = ["ssl"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
