- name_ipv4: "residential_fr_ipv4"
  name_ipv6: "residential_fr_ipv6"
  family: "inet"
  table: "filter"
  asns:
    - "3215"  # orange (ipv4)
    - "5410"  # bouygues
    - "5511"  # orange (ipv6)
    - "12322" # free
    - "15557" # sfr
    - "51207" # free mobile

- name_ipv4: "naughty_ipv4"
  name_ipv6: "naughty_ipv6"
  family: "inet"
  table: "filter"
  asns:
    - "10439"
    - "10439"
    - "12555"
    - "14061"
    - "14618"
    - "15169"
    - "16276"
    - "16509"
    - "17621"
    - "200000"
    - "208137"
    - "214940"
    - "215476"
    - "22612"
    - "24940"
    - "396982"
    - "398324"
    - "4134"
    - "44604"
    - "45102"
    - "47626"
    - "47890"
    - "53514"
    - "55992"
    - "60068"
    - "7497"
    - "8075"
